### ISSUE TITLE
Please support macOS and Linux

### ISSUE THREAD

**Issue by akapu1** [ShahriarShanto/SpeedTest-Tool#1]
I am using MacBook.. so please make a macOS version.

**Comment by ShahriarShanto** [comment]
You can install the official CLI speedtest tool from Ookla
https://www.speedtest.net/apps/cli

```
brew tap teamookla/speedtest
brew update
brew install speedtest --force
```

Then run it, with server id 4235 for internet speed, 14414 for BDIX.

**Comment by azimul-kabir** [comment]
T

> You can install the official CLI speedtest tool from Ookla
> https://www.speedtest.net/apps/cli
> 
> ```
> brew tap teamookla/speedtest
> brew update
> brew install speedtest --force
> ```
> 
> Then run it, with server id 4235 for internet speed, 14414 for BDIX.

Thank you. I have managed to make one for macOS. But it's not standalone executable shell. It needs Homebrew and Speedtest-cli to function.
<img width="674" alt="speedtest-mac" src="https://user-images.githubusercontent.com/29450017/93671871-6c8ffb80-fac8-11ea-80f9-dcdf185a23cf.png">

**Comment by ShahriarShanto** [comment]
Amazing! Good job bro
